spring:
  datasource:
    url: jdbc:mysql://114.115.209.223:3306/sky_eye_system
    username: remoteuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 3
      host: 114.115.209.223
      port: 6379
      connect-timeout: 10s