spring:
  datasource:
    url: jdbc:mysql://192.168.31.40:3306/sky_eye_system
    username: sky_eye_system
    password: sky_eye_system
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 3
      host: 192.168.31.40
      port: 6379
      connect-timeout: 10s
      password: dsx05117218
